/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Claim } from "./Claim";
export * as factories from "./factories";
export { Claim__factory } from "./factories/Claim__factory";
